# Generated by Django 3.0.5 on 2020-11-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='default_page',
            field=models.BooleanField(default=False),
        ),
    ]
