# Generated by Django 3.2.1 on 2021-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='description',
        ),
        migrations.AlterField(
            model_name='admin',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
