# Generated by Django 3.2.1 on 2021-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210509_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='admin',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
