# Generated by Django 3.2.1 on 2021-05-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210515_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
