# Generated by Django 3.0.5 on 2020-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201106_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='unknown', max_length=80),
        ),
    ]
