# Generated by Django 3.2.1 on 2021-05-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='full_name',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='bio',
        ),
        migrations.AddField(
            model_name='admin',
            name='desc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
