# Generated by Django 3.0.5 on 2020-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201124_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='button1_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='button2_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='default/contact.png', null=True, upload_to='contact/'),
        ),
    ]
