# Generated by Django 3.2.1 on 2021-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210509_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='dribble',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='full_name',
            field=models.CharField(blank=True, help_text='full name of owner', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='github',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='gitlab',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='greeting',
            field=models.CharField(blank=True, default='Hi%20there', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='append 91 infront of your number eg 919917956610', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='quora',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='reddit',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='telegram',
            field=models.URLField(blank=True, help_text='https://t.me/username', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='title',
            field=models.CharField(blank=True, help_text='title of the blog', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='unsplash',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='youtube',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='dribble',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='gitlab',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='quora',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='reddit',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='telegram',
            field=models.URLField(blank=True, help_text='https://t.me/username', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='unsplash',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='youtube',
            field=models.URLField(blank=True, help_text='URL of the profile', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text="don't edit this, if you don't know what you are doing", max_length=100, unique_for_date='publish'),
        ),
    ]
