# Generated by Django 3.2.1 on 2021-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210516_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, default='default/admin.png', help_text='image preview in admin panel might look either condensed or pixelated, ignore that', null=True, upload_to='admin/'),
        ),
    ]
