# Generated by Django 3.0.5 on 2020-11-09 08:46

from django.db import migrations, models
import djrichtextfield.models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201107_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=djrichtextfield.models.RichTextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
