# Generated by Django 3.2.1 on 2021-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_admin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='anonymous', max_length=80),
        ),
    ]
