# Generated by Django 3.0.5 on 2020-11-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20201111_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
        migrations.DeleteModel(
            name='UrlHit',
        ),
    ]
