# Generated by Django 3.0.5 on 2020-11-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20201111_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
