# Generated by Django 3.0.5 on 2020-11-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
