# Generated by Django 3.0.5 on 2020-11-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20201112_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor',
            new_name='Viewer',
        ),
        migrations.RenameField(
            model_name='viewer',
            old_name='visitor',
            new_name='viewer',
        ),
    ]
