# Generated by Django 3.0.5 on 2020-11-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_post_unique_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='date_last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewer',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AddField(
            model_name='viewer',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='viewer',
            field=models.GenericIPAddressField(default=None),
        ),
    ]
