# Generated by Django 3.0.5 on 2020-11-13 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20201113_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='viewer',
        ),
        migrations.AddField(
            model_name='viewer',
            name='ip',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='viewer',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viewer',
            name='post',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viewer',
            name='session',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
