# Generated by Django 3.0.5 on 2020-11-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20201113_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewer',
            new_name='History',
        ),
    ]
