# Generated by Django 3.0.5 on 2020-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20201113_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
