# Generated by Django 3.0.5 on 2020-11-13 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20201113_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
