# Generated by Django 3.0.5 on 2020-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20201114_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
