# Generated by Django 3.0.5 on 2020-11-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_author_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
