# Generated by Django 3.0.5 on 2020-11-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20201114_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='user_agent',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
