# Generated by Django 3.0.5 on 2020-11-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_viewer_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
