# Generated by Django 3.0.5 on 2020-11-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_auto_20201115_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='viewer',
            name='ua_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
