# Generated by Django 3.0.5 on 2020-11-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20201115_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='ua_raw',
            field=models.TextField(blank=True, help_text='Client User-Agent HTTP header'),
        ),
    ]
