# Generated by Django 3.0.5 on 2020-11-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20201115_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='ua_raw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
