# Generated by Django 3.0.5 on 2020-11-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20201115_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='ua_raw',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/blog_cover.jpg', null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
