# Generated by Django 3.0.5 on 2020-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20201115_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='default/author.png', upload_to='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default/blog.png', upload_to='blog/%Y/%m/%d/'),
        ),
    ]
