# Generated by Django 3.0.5 on 2020-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20201116_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='default/author_dp.jpg', null=True, upload_to='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/blog_cover.jpg', null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
