# Generated by Django 3.0.5 on 2020-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20201117_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='default/author.png', null=True, upload_to='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/blog.png', null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
