# Generated by Django 3.0.5 on 2020-11-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_auto_20201117_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='avatar',
            new_name='image',
        ),
    ]
