# Generated by Django 3.0.5 on 2020-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_auto_20201117_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='default/author.png', null=True, upload_to='author/'),
        ),
    ]
