# Generated by Django 3.0.5 on 2020-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_auto_20201118_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='default/author.png', null=True, upload_to='author')),
                ('status', models.TextField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True, unique=True)),
                ('twitter', models.URLField(blank=True, null=True, unique=True)),
                ('reddit', models.URLField(blank=True, null=True, unique=True)),
                ('facebook', models.URLField(blank=True, null=True, unique=True)),
                ('github', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
