# Generated by Django 3.0.5 on 2020-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_auto_20201120_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='greeting',
            field=models.CharField(blank=True, default='Hi Priyanshu', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.PositiveIntegerField(default=9917956610),
        ),
    ]
