# Generated by Django 3.0.5 on 2020-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_auto_20201120_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='greeting',
            field=models.CharField(blank=True, default='Hi%20Priyanshu', max_length=100, null=True),
        ),
    ]
