# Generated by Django 3.0.5 on 2020-11-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20201120_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.PositiveIntegerField(default=919917956610),
        ),
    ]
