# Generated by Django 3.0.5 on 2020-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_auto_20201120_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('button1_title', models.CharField(blank=True, max_length=15, null=True)),
                ('button1_url', models.URLField(blank=True, null=True, unique=True)),
                ('button2_title', models.CharField(blank=True, max_length=15, null=True)),
                ('button2_url', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='me/me.png', upload_to='me/')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('number', models.PositiveIntegerField(default=919917956610)),
                ('greeting', models.CharField(blank=True, default='Hi%20Priyanshu', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True, unique=True)),
                ('twitter', models.URLField(blank=True, null=True, unique=True)),
                ('reddit', models.URLField(blank=True, null=True, unique=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('github', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
