# Generated by Django 3.0.5 on 2020-11-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_auto_20201120_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='facebook',
            new_name='telegram',
        ),
    ]
